project_id = "qnupinrsetomnsdchhfa"

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.create-session-payment]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions]
timeout = 30
memory = 512
